# Generated by Django 5.0.2 on 2024-02-27 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_remove_baseuser_is_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
